package eu.siacs.conversations.crypto.axolotl;

import android.content.Context;
import android.net.Uri;

import org.whispersystems.libsignal.IdentityKeyPair;
import org.whispersystems.libsignal.InvalidKeyException;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import javax.crypto.AEADBadTagException;
import javax.crypto.Cipher;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;

import eu.siacs.conversations.entities.Account;
import eu.siacs.conversations.utils.CryptoHelper;
import eu.siacs.conversations.xmpp.Jid;

/**
 * Portable backup for the long-lived OMEMO identity only.
 *
 * <p>This deliberately does not clone the Signal/OMEMO device state. The registration id,
 * signed pre-key, one-time pre-keys and sessions are regenerated by the existing AxolotlService
 * after restore. This keeps two installations from sharing one ratchet/device id.</p>
 *
 * <p>The file is encrypted with the XMPP account password using PBKDF2 and AES-256-GCM. UI code
 * additionally requires Android device credentials before export/import. The device credential is
 * an authorization gate; it is not used as a portable encryption key because Android Keystore
 * keys cannot be moved to a new phone.</p>
 */
public final class OmemoIdentityBackup {

    public static final String MIME_TYPE = "application/x-neocont-omemo-identity";
    public static final String EXTENSION = ".nkb";

    private static final String MAGIC = "NEOCONT-OMEMO-IDENTITY";
    private static final int VERSION = 1;
    private static final int SALT_BYTES = 16;
    private static final int IV_BYTES = 12;
    private static final int KEY_BITS = 256;
    private static final int PBKDF2_ITERATIONS = 200_000;
    private static final int MAX_CIPHERTEXT_BYTES = 16 * 1024;

    private OmemoIdentityBackup() {}

    public static final class Header {
        public final Jid jid;
        public final long createdAt;
        private final int iterations;
        private final byte[] salt;
        private final byte[] iv;

        private Header(
                final Jid jid,
                final long createdAt,
                final int iterations,
                final byte[] salt,
                final byte[] iv) {
            this.jid = jid;
            this.createdAt = createdAt;
            this.iterations = iterations;
            this.salt = salt;
            this.iv = iv;
        }
    }

    public static final class RestoredIdentity {
        public final IdentityKeyPair identityKeyPair;
        public final String fingerprint;
        public final Header header;

        private RestoredIdentity(
                final IdentityKeyPair identityKeyPair,
                final String fingerprint,
                final Header header) {
            this.identityKeyPair = identityKeyPair;
            this.fingerprint = fingerprint;
            this.header = header;
        }
    }

    public static final class WrongPasswordOrCorruptBackupException extends GeneralSecurityException {
        public WrongPasswordOrCorruptBackupException(final Throwable cause) {
            super(cause);
        }
    }

    public static String suggestedFilename(final Account account) {
        final String date = new SimpleDateFormat("yyyyMMdd-HHmm", Locale.US).format(new Date());
        final String jid =
                account.getJid()
                        .asBareJid()
                        .toString()
                        .replaceAll("[^A-Za-z0-9._@-]", "_");
        return "NeoCont-keys-" + jid + "-" + date + EXTENSION;
    }

    public static Header readHeader(final Context context, final Uri uri) throws IOException {
        try (InputStream raw = context.getContentResolver().openInputStream(uri)) {
            if (raw == null) {
                throw new IOException("Unable to open backup");
            }
            try (DataInputStream input = new DataInputStream(new BufferedInputStream(raw))) {
                return readHeader(input);
            }
        }
    }

    public static void exportBackup(
            final Context context,
            final Account account,
            final Uri uri,
            final byte[] serializedIdentity)
            throws IOException, GeneralSecurityException {
        final String password = account.getPassword();
        if (password == null || password.isEmpty()) {
            throw new GeneralSecurityException("Account password is not available");
        }
        if (serializedIdentity == null || serializedIdentity.length == 0) {
            throw new GeneralSecurityException("OMEMO identity is not available");
        }

        final SecureRandom random = new SecureRandom();
        final byte[] salt = new byte[SALT_BYTES];
        final byte[] iv = new byte[IV_BYTES];
        random.nextBytes(salt);
        random.nextBytes(iv);

        final String bareJid = account.getJid().asBareJid().toString();
        final long createdAt = System.currentTimeMillis();
        final String fingerprint;
        try {
            fingerprint =
                    CryptoHelper.bytesToHex(
                            new IdentityKeyPair(serializedIdentity)
                                    .getPublicKey()
                                    .serialize());
        } catch (final InvalidKeyException e) {
            throw new GeneralSecurityException("Invalid OMEMO identity", e);
        }

        final ByteArrayOutputStream payloadBytes = new ByteArrayOutputStream();
        try (DataOutputStream payload = new DataOutputStream(payloadBytes)) {
            payload.writeInt(serializedIdentity.length);
            payload.write(serializedIdentity);
            payload.writeUTF(fingerprint);
        }

        final SecretKeySpec key = deriveKey(password, salt, PBKDF2_ITERATIONS);
        final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, key, new GCMParameterSpec(128, iv));
        cipher.updateAAD(aad(bareJid, createdAt));
        final byte[] ciphertext = cipher.doFinal(payloadBytes.toByteArray());

        try (OutputStream raw = context.getContentResolver().openOutputStream(uri, "w")) {
            if (raw == null) {
                throw new IOException("Unable to create backup");
            }
            try (DataOutputStream output = new DataOutputStream(new BufferedOutputStream(raw))) {
                output.writeUTF(MAGIC);
                output.writeInt(VERSION);
                output.writeUTF(bareJid);
                output.writeLong(createdAt);
                output.writeInt(PBKDF2_ITERATIONS);
                output.writeInt(salt.length);
                output.write(salt);
                output.writeInt(iv.length);
                output.write(iv);
                output.writeInt(ciphertext.length);
                output.write(ciphertext);
                output.flush();
            }
        }
    }

    public static RestoredIdentity readBackup(
            final Context context, final Account account, final Uri uri)
            throws IOException, GeneralSecurityException {
        final String password = account.getPassword();
        if (password == null || password.isEmpty()) {
            throw new GeneralSecurityException("Account password is not available");
        }

        try (InputStream raw = context.getContentResolver().openInputStream(uri)) {
            if (raw == null) {
                throw new IOException("Unable to open backup");
            }
            try (DataInputStream input = new DataInputStream(new BufferedInputStream(raw))) {
                final Header header = readHeader(input);
                if (!header.jid.asBareJid().equals(account.getJid().asBareJid())) {
                    throw new GeneralSecurityException("Backup belongs to another account");
                }
                final int ciphertextLength = input.readInt();
                if (ciphertextLength <= 0 || ciphertextLength > MAX_CIPHERTEXT_BYTES) {
                    throw new IOException("Invalid backup payload length");
                }
                final byte[] ciphertext = new byte[ciphertextLength];
                input.readFully(ciphertext);

                final SecretKeySpec key = deriveKey(password, header.salt, header.iterations);
                final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
                cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(128, header.iv));
                cipher.updateAAD(aad(header.jid.asBareJid().toString(), header.createdAt));

                final byte[] plaintext;
                try {
                    plaintext = cipher.doFinal(ciphertext);
                } catch (final AEADBadTagException e) {
                    throw new WrongPasswordOrCorruptBackupException(e);
                }

                try (DataInputStream payload =
                        new DataInputStream(new ByteArrayInputStream(plaintext))) {
                    final int identityLength = payload.readInt();
                    if (identityLength <= 0 || identityLength > 4096) {
                        throw new IOException("Invalid identity length");
                    }
                    final byte[] identityBytes = new byte[identityLength];
                    payload.readFully(identityBytes);
                    final String storedFingerprint = payload.readUTF();
                    final IdentityKeyPair identityKeyPair;
                    try {
                        identityKeyPair = new IdentityKeyPair(identityBytes);
                    } catch (final InvalidKeyException e) {
                        throw new GeneralSecurityException("Invalid OMEMO identity in backup", e);
                    }
                    final String actualFingerprint =
                            CryptoHelper.bytesToHex(identityKeyPair.getPublicKey().serialize());
                    if (!actualFingerprint.equalsIgnoreCase(storedFingerprint)) {
                        throw new GeneralSecurityException("OMEMO identity fingerprint mismatch");
                    }
                    return new RestoredIdentity(identityKeyPair, actualFingerprint, header);
                }
            } catch (final EOFException e) {
                throw new IOException("Truncated OMEMO identity backup", e);
            }
        }
    }

    private static Header readHeader(final DataInputStream input) throws IOException {
        final String magic = input.readUTF();
        if (!MAGIC.equals(magic)) {
            throw new IOException("Not an OMEMO identity backup");
        }
        final int version = input.readInt();
        if (version != VERSION) {
            throw new IOException("Unsupported OMEMO identity backup version: " + version);
        }
        final Jid jid;
        try {
            jid = Jid.of(input.readUTF()).asBareJid();
        } catch (final IllegalArgumentException e) {
            throw new IOException("Invalid JID in backup", e);
        }
        final long createdAt = input.readLong();
        final int iterations = input.readInt();
        if (iterations < 10_000 || iterations > 2_000_000) {
            throw new IOException("Invalid key derivation parameters");
        }
        final byte[] salt = readSizedBytes(input, SALT_BYTES, 64, "salt");
        final byte[] iv = readSizedBytes(input, IV_BYTES, 32, "iv");
        return new Header(jid, createdAt, iterations, salt, iv);
    }

    private static byte[] readSizedBytes(
            final DataInputStream input,
            final int expectedLength,
            final int maxLength,
            final String name)
            throws IOException {
        final int length = input.readInt();
        if (length != expectedLength || length > maxLength) {
            throw new IOException("Invalid " + name + " length");
        }
        final byte[] bytes = new byte[length];
        input.readFully(bytes);
        return bytes;
    }

    private static SecretKeySpec deriveKey(
            final String password, final byte[] salt, final int iterations)
            throws GeneralSecurityException {
        final PBEKeySpec keySpec = new PBEKeySpec(password.toCharArray(), salt, iterations, KEY_BITS);
        try {
            final SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
            return new SecretKeySpec(factory.generateSecret(keySpec).getEncoded(), "AES");
        } finally {
            keySpec.clearPassword();
        }
    }

    private static byte[] aad(final String bareJid, final long createdAt) {
        return (MAGIC + "|" + VERSION + "|" + bareJid + "|" + createdAt)
                .getBytes(StandardCharsets.UTF_8);
    }
}
