// Copyright (c) 2026 rockcutto
// SPDX-License-Identifier: MPL-2.0
// Provenance: NATIVE-CORE

package eu.siacs.conversations.security.recovery

import java.nio.charset.StandardCharsets

/**
 * NeoCont Recovery KEK v1.
 *
 * Recovery input is 128 bits generated by CSPRNG, not a human password. HKDF therefore provides
 * extraction/domain separation; it is intentionally not a password-hardening KDF.
 */
object RecoveryKekKdfV1 {
    const val KDF_VERSION: Int = 1
    const val KDF_ID: String = "HKDF-SHA256"
    const val SALT_BYTES: Int = 32
    const val KEK_BYTES: Int = 32

    internal fun derive(
        secret: RecoverySecret,
        salt: ByteArray,
    ): RecoveryKek =
        derive(secret, salt, RecoveryPhraseFormats.BIP39_EN_V1)

    internal fun derive(
        secret: RecoverySecret,
        salt: ByteArray,
        phraseFormat: RecoveryPhraseFormat,
    ): RecoveryKek {
        require(salt.size == SALT_BYTES) { "Recovery KDF salt must be 32 bytes" }
        val info =
            (
                phraseFormat.kdfDomain +
                    "|RecoveryKEK|v1" +
                    "|phrase=" + phraseFormat.formatVersion +
                    "|dictionary=" + phraseFormat.dictionaryId +
                    "|wrapper=1"
            ).toByteArray(StandardCharsets.UTF_8)
        val derived =
            try {
                secret.useCopy { input ->
                    HkdfSha256.derive(input, salt, info, KEK_BYTES)
                }
            } finally {
                info.fill(0)
            }
        return RecoveryKek.takeOwnership(derived)
    }
}

internal class RecoveryKek private constructor(
    private val bytes: ByteArray,
) : AutoCloseable {

    internal inline fun <T> useCopy(block: (ByteArray) -> T): T {
        val copy = bytes.copyOf()
        return try {
            block(copy)
        } finally {
            copy.fill(0)
        }
    }

    override fun close() {
        bytes.fill(0)
    }

    override fun toString(): String = "RecoveryKek([REDACTED])"

    companion object {
        internal fun takeOwnership(bytes: ByteArray): RecoveryKek {
            require(bytes.size == RecoveryKekKdfV1.KEK_BYTES)
            return RecoveryKek(bytes)
        }
    }
}
